version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  service-a:
    build: ./serviceA
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
  service-b:
    build: ./serviceB
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq